### ISSUE TITLE
Unable to build tripfind.c

### ISSUE THREAD

**Issue by AXYPB** [Cairnarvon/triptools#1]
All variants of tripfind return this error 1 on build:

```
tripfind.c:91: error: comparison is always true due to limited range of data type
```

**Comment by Cairnarvon** [comment]
That's bizarre. I have no idea why it would be doing that.
What OS are you using and what's the type signature of your `getopt` (`man 3 getopt`, in the Synopsis section)? Which C compiler are you using (if you didn't edit the Makefile it's `gcc`) and what version is it (`gcc --version`)?

(Don't use `tripfind`, anyway. [Tripcode Explorer](http://tripcode.50webs.com/te.html) running under WINE will outperform it dramatically. I keep meaning to write a less useless version but more interesting things keep happening.)

**Comment by AXYPB** [comment]
I'm trying to compile it on a Raspberry Pi (http://raspberrypi.org) running Debian squeeze for ARM. I'm testing the performance of various *nix command line tripcode searchers on the Pi. It is incapable of using WINE.

The Synopsis of `man 3 getopt` reads:

```
       #include <unistd.h>

       int getopt(int argc, char * const argv[],
                  const char *optstring);

       extern char *optarg;
       extern int optind, opterr, optopt;

       #include <getopt.h>

       int getopt_long(int argc, char * const argv[],
                  const char *optstring,
                  const struct option *longopts, int *longindex);

       int getopt_long_only(int argc, char * const argv[],
                  const char *optstring,
                  const struct option *longopts, int *longindex);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       getopt(): _POSIX_C_SOURCE >= 2 || _XOPEN_SOURCE
       getopt_long(), getopt_long_only(): _GNU_SOURCE
```

`gcc --version` returns `gcc (Debian 4.4.5-8) 4.4.5`.

**Comment by Cairnarvon** [comment]
I'm reasonably sure this is a `gcc` bug (the error message just doesn't make any sense), but ad3bef834 should fix the issue, anyway.

(Sorry it took a while, I set up a Raspberry Pi VM for testing.)
